server:
  port: 8091
  servlet:
    context-path: /cck/auth
logging:
  level:
    root: INFO



spring:
  application:
    name: cck-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
        namespace: 519bdb33-f723-40dd-8004-ff59f82aaf82
  jackson:
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cck-auth?characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout: 30000

mybatis-plus:
#  type-enums-package: com.lxbznkj.agent.server.infrastructure.common.enums
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    variables:
      cleanerRoleId: 4
      propertyRoleId: 7
      cleanerManagerRoleId: 8
      cleanerManagerRoleId2: 12
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl